ejodi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('accounts/',include('allauth.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from notification.views import notification

urlpatterns=[
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('logout',views.logout,name='logout'),
    path('profile',views.profile,name='profile'),
    path('notification',notification,name='notification'),
    path('profile/update',views.updateuserprofile,name='updateuserprofile'),
    
    
]

home/models.py
from django.db import models
from django.contrib.auth.models import User


from django.conf import settings

class Gender(models.Model):
    gender = models.CharField(max_length=20)
    def __str__(self):
        return self.gender
    


class UserProfile(models.Model):
    user   = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField()
    gender = models.ForeignKey(Gender,on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="gallery")
    bio = models.CharField(max_length=150)
    location = models.CharField(max_length=200)
    hobby = models.CharField(max_length=200)
    
    def __str__(self):
        return self.user.username
    


class Like(models.Model):
    liked_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    liked_to : models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return '%s Liked %s'%(self.liked_by, self.liked_to)

    


class Ignore(models.Model):
    ignored_by: models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ignored_to: models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return '%s Ignored %s'%(self.ignored_by, self.ignored_to)

notification/models.py
from django.db import models

home/forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'
        exclude = ('user',)
       
    def __init__(self, *args, **kwargs):
        super(UserProfileForm,self).__init__()
        self.fields['gender'].empty_label = 'Select Your Gender'
        self.fields['avatar'].required = False
        self.fields['hobby'].required = False
        self.fields['bio'].required = False
        self.fields['age'].required = False
        self.fields['location'].required = False
        self.fields['gender'].required = False

    
        
        

home/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import auth,User
from django.contrib import messages
from .models import UserProfile
from django.core.files.storage import FileSystemStorage
from .models import UserProfile, Gender
from .forms import UserProfileForm





def index(request):
    
    userdetail = UserProfile.objects.all()
    context ={
        
        'userprofiles':userdetail
    }
    
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.warning(request,'Invalid Syntax')
            return redirect('/')
    else:
        

        return render(request,'home/home.html', context)







def signup(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        pass1 = request.POST['password1']
        pass2 = request.POST['password2']
        if pass1== pass2:
            if User.objects.filter(username=username).exists():
                messages.warning(request,'Username has been taken')
                return redirect('/signup')

            elif User.objects.filter(email=email).exists():
                messages.warning(request,'Email already exist')
                return redirect('/signup')
            else:
                user = User.objects.create_user(username=username,first_name=first_name,last_name=last_name,email=email,password=pass1)
                user.save()
                messages.success(request,"UserCreated")
                return redirect('/')
            return redirect('signup')   
        else:
            messages.error(request,'Password Didnot Matched')
            return redirect('index') 
        
    else:
        return render(request,'home/signup.html')







def logout(request):
    auth.logout(request)
    return redirect('/')







def profile(request):
    
    
    if UserProfile.objects.filter(user=request.user).exists():
        userdetail = UserProfile.objects.get(user =request.user)
    
        context ={
        
        'userprofile': userdetail
        }
        return render(request,'home/profile.html',context)
    else:
        return redirect('updateuserprofile')
    return redirect('index')


def updateuserprofile(request):
    if UserProfile.objects.filter(user=request.user).exists():
        userdetail = UserProfile.objects.get(user =request.user)
        title = "Update You User Profile"
        context ={
        
        'userprofile': userdetail,
        'title': title
        }
        if request.method== 'POST':
                
                
                bio = request.POST['bio']
                userdetail.bio=bio
                
                
                age = request.POST['age']
                userdetail.age = age
                
                
                hobby = request.POST['hobby']
                userdetail.hobby = hobby
                location = request.POST['location']
                userdetail.location = location
                userdetail.save()
                # print(gender)
                # location = request.POST['location']
                # if request.POST['avatar']:
                #     avatar = request.FILES['avatar']
                # userprofile = UserProfile(user=user,bio=bio,age=age,gender=gender,location=location,hobby=hobby,avatar=avatar)
                # print(userprofile)
                
                return redirect('profile')
        

        return render(request,'home/update.html',context)
    else:
        
        if request.method == 'GET':
            form = UserProfileForm()
            
        
            title = "Create Your Profile"
            
            
            return render(request, 'home/update.html',{'form':form,'title':title})


            
        else:
            if request.method== 'POST':
                gender =''
                
                bio = request.POST['bio']
                user = request.user
                age = request.POST['age']
                avatar = request.FILES['avatar']
                gender = request.POST['gender']
                print(gender)
                gender = Gender.objects.get(gender= gender)
                print(gender)
                location = request.POST['location']
                hobby = request.POST['hobby']
                userprofile = UserProfile(user=user,bio=bio,age=age,gender=gender,location=location,hobby=hobby,avatar=avatar)
                userprofile.save()
                
                return redirect('profile')
            else:
            
                return render(request,'home/profile.html')
                
            
        
    return redirect('index')
    

notification/views.py
from django.shortcuts import render

def notification(request):
    return render(request,'home/notification.html')

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" >
    <title>Document</title>
    <!-- CSS only -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="js" href="{% static 'js/home.js' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
    
{% if user.is_authenticated %}

<body>

 
  
<nav class="navbar navbar-fixed navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'index' %}" >Ejodi</a>
    
      <ul class="navbar-nav mr-auto">
        
        
      </ul>
      <div class="form-inline my-2 my-lg-0 p-2">
        <a href="{% url 'profile' %}" class="btn btn-outline-danger mr-2 my-sm-0"><span class="fa fa-user"> </span></a><br>
        <a href="" class="btn btn-outline-danger mr-2 my-sm-0"><span class="fa fa-envelope"> </span></a><br>
        <a href="{% url 'notification' %}" class="btn btn-outline-danger mr-2 my-sm-0"><span class="fa fa-newspaper-o"> </span></a><br>
        <a href="{% url 'logout' %}" class="btn btn-outline-danger mr-2 my-sm-0"><span class="fa fa-sign-out"> </span></a>
        
      </div>
    
  </nav>
<hr>


{% else %}
<div></div>
{% endif %}
{% block content %}


{% endblock content %}

</body>


</html>

home/templates/home/home.html
{% extends "home/base.html" %}
{% load static %}

{% load socialaccount %}
{% providers_media_js %}
{% block content %}


<!-- This is when user is is_authenticated and home screen appear -->


<!-- This is for login and part -->


{% if user.is_authenticated %}

<style>
    #person_image{
    background-repeat: repeat-x;    
    margin-left: 5%;
    margin-top: 10%;
    
}

#person_image .but1{    
   
    line-height: 1%;
    margin-top: 1%;
    margin-left: 1%;
    margin-right:1%;
    display:inline-block;
    position:relative;
}

#person_image .btn1 {
    position:absolute;
    bottom: 5%;
    left: 5%;
}


#person_image .btn2 {
    position:absolute;
    bottom: 5%;
    right: 5%;
}
</style>
{% for userprofile in userprofiles %}


<!-- Remove Superuser From Home Page -->
{% if userprofile.user.first_name and userprofile.user.last_name and userprofile.user.email %}  
<form method="POST">
    {% csrf_token %}
<div class="container card mt-5 pt-6">
    <div class="row ">
        <div class="col-md-6">
            

<div id="person_image">
<div class="but1">
<!--Card image-->
<img class="img-fluid" src="{{ userprofile.avatar.url }}" alt="Test Image">
<!--/.Card image-->
<button onclick="liked()" id='like' class="btn btn1 btn-floating btn-danger"><i class="fa fa-heart"></i></a>
<button onclick="ignored()" class="btn btn2 btn-floating btn-warning"><i class="fa fa-remove"></i></a>
</div>
</div>



        </div>
        <div class="card-body">
<div class="col-12 card-title">
  <h4> <b> {{ userprofile.user.first_name }} {{ userprofile.user.last_name }}</b></h4>
    

</div>
<p class="card-text">{{ userprofile.bio }}</p><br>
<p class="card-text">{{ userprofile.location }}</p>

</div>
</div>
</div>

</form>
{% endif %}
{% endfor %}





















{% else %}

    <!-- This is when user is not is_authenticated -->





































<div class="container">
     
    <img src= "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20190710102234/download3.png"
        width="90" height="80" alt="" style="float: right;"> 
    <div class="login-form" style="float: left;">
        <form method="POST">
            {% csrf_token %}
            {% if messages %}
                <div class=" messages ">
                    {% for message in messages %}
                        <div  class="alert alert-{{message.tags}}">
                            {{ message }}
                        </div>
                    {% endfor %}
                    </div>
            {% endif %}
            <div class="justify-content-center">
    
                <h2 class="justify-content-center">Login</h2>   
            </div>
            
            <div class="form-group">
                <div class="input-group">
                    
                    <input type="text"  class="form-control" name="username" placeholder="Username" required="required">				
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    
                    <input input type="password"  id="myInput" class="form-control" name="password" placeholder="Password" required="required">				
                </div>
            </div>        
            <div class="form-group">
                <input type="checkbox" onclick="myFunction()">Show Password
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-success login-btn btn-block">Login</button>
            </div>
            <div class="text-center social-btn">
                <a href="#" class="btn btn-outline-primary"><i class="fa fa-facebook"></i>&nbsp; Facebook</a>
                
                <a href="#" class="btn btn-outline-danger"><i class="fa fa-google"></i>&nbsp; Google</a>
            </div>
        </form>
        <p class="text-center text-muted small">Don't have an account? <a href="{% url 'signup' %} ">Sign up here!</a></p>
    </div>
   
</div>

{% endif %}

<script>
    function myFunction() {
      var x = document.getElementById("myInput");
      if (x.type === "password") {
        x.type = "text";
      } else {
        x.type = "password";
      }
    }

    $(function() {
  $("like").on("click",function(e) {
    e.preventDefault(); // cancel the link itself
    $.post(this.href,function(data) {
      $("#someContainer").html(data);
    });
  });
});
    
    </script>
    
{% endblock content %}



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

home/templates/home/notification.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<div class="container">

    <h3 class="mb-5">Notification</h3>
    <table class="table">
        <thead>
          <tr class="">
            
            <th scope="col-8">Detail</th>
            <th scope="col-2">Time</th>
            
          </tr>
        </thead>
        <tbody>
          <tr>
            
            <td class="border border-right">Mark</td>
            <td class="border border-right">Otto</td>
            
          </tr>
          <tr>
           
            <td class="border border-right">Jacob</td>
            <td class="border border-right">Thornton</td>
            
          </tr>
          <tr>
           
            <td class="border border-right">Larry</td>
            <td class="border border-right">the Bird</td>
            
          </tr>
        </tbody>
      </table>



</div>
{% endblock content %}

home/templates/home/profile.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

  
    <h2 style="text-align:center">Profile</h2>
    
    <div class="card">
      
      <img src="{{ userprofile.avatar.url }}" alt="{{ user.first_name }} Image" style="width:100%">
      <h1>{{user.username}}
      </h1> <a href="{% url 'updateuserprofile' %}" style="float: left;" class="btn"><span class="fa fa-edit"></span></a>
      
      <p><b>Bio</b> {{ userprofile.bio }}</p>
      <p><b>Location</b> {{ userprofile.location }}</p>
      <p><b>Age</b>: {{ userprofile.age }}</p>
      <p><b>Hobby</b>: {{ userprofile.hobby }}</p>
      <div style="margin: 24px 0;">
        <hr>
        <a href="#"><i class="fa fa-dribbble"></i></a> 
        <a href="#"><i class="fa fa-twitter"></i></a>  
        <a href="#"><i class="fa fa-linkedin"></i></a>  
        <a href="#"><i class="fa fa-facebook"></i></a> 
        
      </div>
      
    </div>
    
<style>
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      max-width: 300px;
      margin: auto;
      text-align: center;
      font-family: arial;
    }
    
    .title {
      color: grey;
      font-size: 18px;
    }
    
    
    
    a {
      text-decoration: none;
      font-size: 22px;
      color: black;
    }
    
    button:hover, a:hover {
      opacity: 0.7;
    }
    </style>
{% endblock content %}

home/templates/home/signup.html
{% extends "home/base.html" %}
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

{% block content %}
<div class="container">

    {% if messages %}
<ul style="text-decoration: none;" class=" messages ">
    {% for message in messages %}
    <li      {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

    <div class="Signup-form">
        <form  method="POST">
            {% csrf_token %}
            <div class="justify-content-center">
    
                <h2 class="justify-content-center">Signup</h2>   
            </div>
            
            <div class="form-group">
                <div class="input-group">
                    
                    <input type="text" class="form-control mt-3" name="username" placeholder="Username" required="required">				
                </div>
                <div class="input-group">
                    
                    <input type="text" class="form-control mt-3" name="first_name" placeholder="First Name" required="required">				
                </div>
                <div class="input-group">
                    
                    <input type="text" class="form-control mt-3" name="last_name" placeholder="Last Name" required="required">				
                </div>


                <div class="input-group">
                    
                    <input type="email" class="form-control mt-3" name="email" placeholder="Enter Your Email" required="required">				
                </div>

            </div>








            <div class="form-group">
                

                <div class="input-group">
                    
                    <input type="password" class="form-control mt-3" name="password1" placeholder="Password" required="required">				
                </div>



                <div class="input-group">
                    
                    <input type="password" class="form-control mt-3" name="password2" placeholder="Confirm Password" required="required">				
                </div>



            </div>        
            <div class="form-group">
                <button type="submit" class="btn btn-outline-success Signup-btn btn-block">Signup</button>
            </div>
            <div class="text-center social-btn">
                <a href="{% provider_login_url 'facebook' method='oauth2' %}" class="btn btn-outline-primary"><i class="fa fa-facebook"></i>&nbsp; Facebook</a>
                
                <a href="#" class="btn btn-outline-danger"><i class="fa fa-google"></i>&nbsp; Google</a>
            </div>
        </form>
        <p class="text-center text-muted small">Have an account? <a href="{% url 'index'  %}""  >Login here!</a></p>
    </div>
    

</div>

   


{% endblock content %}

home/templates/home/update.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="container">
  <b> <h3>{{ title }}</h3></b>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    

<div id="div_id_age" class="form-group"> <label for="id_age" class="">
                <b>Age </b>
            </label> <div class=""> <input type="number" name="age" value='{{ userprofile.age }}' class="numberinput form-control" id="id_age"> </div> </div> 
            {% if userprofile.gender %}
            <div></div>
            {% else %}
            <div id="div_id_gender" class="form-group"> <label for="id_gender" class="">

                <b> Gender</b>
            </label> <div class=""> <select name="gender" class="select form-control" id="id_gender"> <option value="" selected> {% if userprofile.gender %}  {{userprofile.gender}} {% else %} Select Your Gender {% endif %} </option> <option value="Male">Male</option> <option value="Female">Female</option> <option value="Other">Other</option> <option value="Prefer Not To Say">Prefer Not To Say</option>

</select> </div> </div>

{% endif %}
{% if userprofile.avatar %}
<div></div>
{% else %}
 <div id="div_id_avatar" class="form-group"> <label for="id_avatar" class="">
  <b>Choose Your Profile Picture </b>
            </label> <div class=""> <input type="file" name="avatar" accept="image/*" class="clearablefileinput form-control-file"  id="id_avatar"> </div> </div>
{% endif %}
            
            <div id="div_id_bio" class="form-group"> <label for="id_bio" class="">
               <b>Bio</b>
            </label> <div class=""> <input type="text" value="{{ userprofile.bio }}" name="bio" maxlength="150" class="textinput textInput form-control" id="id_bio"> </div> </div> <div id="div_id_location" class="form-group"> <label for="id_location" class="">
                <b>Location</b>
            </label> <div class=""> <input type="text" name="location" value="{{ userprofile.location }}" maxlength="200" class="textinput textInput form-control" id="id_location"> </div> </div> <div id="div_id_hobby" class="form-group"> <label for="id_hobby" class="">
                <b>Hobby</b>
            </label> <div class=""> <input type="text" name="hobby" value="{{ userprofile.hobby }}" maxlength="200" class="textinput textInput form-control" id="id_hobby"> </div> </div>

   
    <button class="btn btn-success" type="submit">Submit</button>
  </form>
  

</div>


{% endblock content %}

home/templates/home/userprofile.html
{% extends "home/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{forms | crispy}}
    <button class="btn btn-success" type="submit">Submit</button>
</form>

{% endblock content %}